name: Build Professional Small APKs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true

    - name: Generate Platform Folders
      run: flutter create .

    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK (Split per ABI & Obfuscated)
      run: flutter build apk --release --split-per-abi --obfuscate --split-debug-info=build/app/outputs/symbols

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-apks
        path: build/app/outputs/flutter-apk/app-*-release.apk
